### ISSUE TITLE
Windows compatibility with postinstall

### ISSUE THREAD

**Issue by MumblesNZ** [krzysiekpiasecki/ngNewAge#9]
Hey,

Just FYI for anyone using windows trying to install this with NPM. NPM install will fail with the postinstall command in package.json having unix reference  "postinstall": "./node_modules/bower/bin/bower install". For windows if you change it to "postinstall": "bower install" everything should work fine. 

Thanks.

**Comment by krzysiekpiasecki** [comment]
@MumblesNZ Thanks, correct. There is a new branch 2.0 where all dependencies will be installed with npm.
